# Use the minimal Python 3.13.2 image
FROM python:3.13.5-slim

ENV PYTHONPATH=/app

# Install required OS packages
RUN apt-get update && apt-get install -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory
WORKDIR /app

# Copy Python dependencies
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY ai/. ai/
COPY bot/. bot/
COPY tools/. tools/
COPY ai_start.sh .

# Make the script executable
RUN chmod +x ai_start.sh

# Use start.sh as entrypoint
ENTRYPOINT ["./ai_start.sh"]